-----------------------------------------------------------------------------------------------
-- AUTOR......: CLOVIS
-- DATA.......: 23/07/14
-- DESCRICAO..: NOVOS ATRIBUTOS PARA NOTA FISCAL ELETRÔNICA
-- SOLICITAÇÃO: 51398 (PRASIST)
-- TELA.......: ESTOQUE        - 0039 - CADASTRO DE MERCADORIAS
-- TELA.......: VENDAS         - 0143 - CADASTRO DE PEDIDOS
-- TELA.......: VENDAS         - 0151 - EMISSÃO NOTA SAIDA
-- TELA.......: VENDAS         - 0152 - EMISSÃO NOTA DEVOLUÇÃO
-- TELA.......: TELEVENDAS     - 0236 - CADASTRO TELEVENDAS
-- TELA.......: LIVROS FISCAIS - 0715 - NOTA FISCAL ELETRONICA
-----------------------------------------------------------------------------------------------

ALTER TABLE SERVMERC ADD UNTRIBUTAVEL CHAR(3) NULL
GO

ALTER TABLE ITENSPED ADD QTDTRIBUTAVEL MONEY NULL
GO

ALTER TABLE ITENSPED ADD VLRTRIBUTAVEL MONEY NULL
GO

ALTER TABLE ITENSNF ADD QTDTRIBUTAVEL MONEY NULL
GO

ALTER TABLE ITENSNF ADD VLRTRIBUTAVEL MONEY NULL
GO

ALTER TABLE ITENSNFE ADD QTDTRIBUTAVEL MONEY NULL
GO

ALTER TABLE ITENSNFE ADD VLRTRIBUTAVEL MONEY NULL
GO

